name: Tests

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toolz
          pip install sidekick
          pip install markupsafe
          pip install -e .[docs]
      - name: Run tests
        run: python3 -m unittest discover -s tests
